    var jQT = new $.jQTouch({
        icon: 'images/apple-touch-icon-precomposed.png',
        addGlossToIcon: false,
        startupScreen: 'images/apple-touch-startup-image.png',
        statusBar: 'black',
        fixedViewport: 'true',
        fullScreen: 'true',
        useAnimations: 'true',
        initializeTouch: 'body, div.touch, a ',
        touchSelector: '#Tabelle_01, #Tabelle_02, #Tabelle_03',
        preloadImages: [
            'themes/apple/img/back_button.png',
            'themes/apple/img/back_button_clicked.png',
            'themes/apple/img/button_clicked.png',
            'themes/apple/img/grayButton.png',
            'themes/apple/img/whiteButton.png',
            'themes/apple/img/loading.gif',
            'themes/apple/img/pinstripes.png',
            'themes/apple/img/toggle.png',
            'themes/apple/img/toggleOn.png',
            'themes/apple/img/toolbar.png',
            'themes/apple/img/thumb.png',
            'images/apple-touch-icon.png',
            'images/apple-touch-icon-precomposed.png',
            'images/apple-touch-startup-image.png',
						'images/saf_41.gif',
						'images/saf_42.gif',
						'images_slice/01_iR_GUI_qui_C.png',
						'images_slice/02_iR_GUI_adv.png',
						'images_slice/02_iR_GUI_adv_C.png',
						'images_slice/02_iR_GUI_num.png',
						'images_slice/02_iR_GUI_num_C.png',
						'images_slice/02_iR_GUI_qui.png',
						'images_slice/02_iR_GUI_qui_C.png',
						'images_slice/03_iR_GUI_adv.png',
						'images_slice/03_iR_GUI_adv_C.png',
						'images_slice/03_iR_GUI_num.png',
						'images_slice/03_iR_GUI_num_C.png',
						'images_slice/03_iR_GUI_qui.png',
						'images_slice/03_iR_GUI_qui_C.png',
						'images_slice/04_iR_GUI_adv.png',
						'images_slice/04_iR_GUI_adv_C.png',
						'images_slice/04_iR_GUI_num.png',
						'images_slice/04_iR_GUI_num_C.png',
						'images_slice/04_iR_GUI_qui.png',
						'images_slice/04_iR_GUI_qui_C.png',
						'images_slice/05_iR_GUI_adv.png',
						'images_slice/05_iR_GUI_adv_C.png',
						'images_slice/05_iR_GUI_num.png',
						'images_slice/05_iR_GUI_num_C.png',
						'images_slice/05_iR_GUI_qui.png',
						'images_slice/05_iR_GUI_qui_C.png',
						'images_slice/06_iR_GUI_adv.png',
						'images_slice/06_iR_GUI_adv_C.png',
						'images_slice/06_iR_GUI_num.png',
						'images_slice/06_iR_GUI_num_C.png',
						'images_slice/06_iR_GUI_qui.png',
						'images_slice/06_iR_GUI_qui_C.png',
						'images_slice/07_iR_GUI_adv.png',
						'images_slice/07_iR_GUI_adv_C.png',
						'images_slice/07_iR_GUI_num.png',
						'images_slice/07_iR_GUI_num_C.png',
						'images_slice/07_iR_GUI_qui.png',
						'images_slice/07_iR_GUI_qui_C.png',
						'images_slice/08_iR_GUI_adv.png',
						'images_slice/08_iR_GUI_adv_C.png',
						'images_slice/08_iR_GUI_num.png',
						'images_slice/08_iR_GUI_num_C.png',
						'images_slice/08_iR_GUI_qui.png',
						'images_slice/08_iR_GUI_qui_C.png',
						'images_slice/09_iR_GUI_adv.png',
						'images_slice/09_iR_GUI_adv_C.png',
						'images_slice/09_iR_GUI_num.png',
						'images_slice/09_iR_GUI_num_C.png',
						'images_slice/09_iR_GUI_qui.png',
						'images_slice/09_iR_GUI_qui_C.png',
						'images_slice/10_iR_GUI_adv.png',
						'images_slice/10_iR_GUI_adv_C.png',
						'images_slice/10_iR_GUI_num.png',
						'images_slice/10_iR_GUI_num_C.png',
						'images_slice/10_iR_GUI_qui.png',
						'images_slice/10_iR_GUI_qui_C.png',
						'images_slice/11_iR_GUI_adv.png',
						'images_slice/11_iR_GUI_adv_C.png',
						'images_slice/11_iR_GUI_num.png',
						'images_slice/11_iR_GUI_num_C.png',
						'images_slice/11_iR_GUI_qui.png',
						'images_slice/11_iR_GUI_qui_C.png',
						'images_slice/12_iR_GUI_adv.png',
						'images_slice/12_iR_GUI_adv_C.png',
						'images_slice/12_iR_GUI_num.png',
						'images_slice/12_iR_GUI_num_C.png',
						'images_slice/12_iR_GUI_qui.png',
						'images_slice/12_iR_GUI_qui_C.png',
						'images_slice/13_iR_GUI_adv.png',
						'images_slice/13_iR_GUI_adv_C.png',
						'images_slice/13_iR_GUI_num.png',
						'images_slice/13_iR_GUI_num_C.png',
						'images_slice/13_iR_GUI_qui.png',
						'images_slice/13_iR_GUI_qui_C.png',
						'images_slice/14_iR_GUI_adv.png',
						'images_slice/14_iR_GUI_adv_C.png',
						'images_slice/14_iR_GUI_num.png',
						'images_slice/14_iR_GUI_num_C.png',
						'images_slice/14_iR_GUI_qui.png',
						'images_slice/14_iR_GUI_qui_C.png',
						'images_slice/15_iR_GUI_adv.png',
						'images_slice/15_iR_GUI_adv_C.png',
						'images_slice/15_iR_GUI_num.png',
						'images_slice/15_iR_GUI_num_C.png',
						'images_slice/15_iR_GUI_qui.png',
						'images_slice/15_iR_GUI_qui_C.png',
						'images_slice/16_iR_GUI_adv.png',
						'images_slice/16_iR_GUI_adv_C.png',
						'images_slice/16_iR_GUI_num.png',
						'images_slice/16_iR_GUI_num_C.png',
						'images_slice/16_iR_GUI_qui.png',
						'images_slice/16_iR_GUI_qui_C.png',
						'images_slice/17_iR_GUI_adv.png',
						'images_slice/17_iR_GUI_adv_C.png',
						'images_slice/17_iR_GUI_num.png',
						'images_slice/17_iR_GUI_num_C.png',
						'images_slice/17_iR_GUI_qui.png',
						'images_slice/17_iR_GUI_qui_C.png',
						'images_slice/18_iR_GUI_adv.png',
						'images_slice/18_iR_GUI_adv_C.png',
						'images_slice/18_iR_GUI_num.png',
						'images_slice/18_iR_GUI_num_C.png',
						'images_slice/18_iR_GUI_qui.png',
						'images_slice/18_iR_GUI_qui_C.png',
						'images_slice/19_iR_GUI_num.png',
						'images_slice/19_iR_GUI_num_C.png',
						'images_slice/19_iR_GUI_qui.png',
						'images_slice/19_iR_GUI_qui_C.png',
						'images_slice/20_iR_GUI_num.png',
						'images_slice/20_iR_GUI_num_C.png',
						'images_slice/20_iR_GUI_qui.png',
						'images_slice/20_iR_GUI_qui_C.png',
						'images_slice/21_iR_GUI_num.png',
						'images_slice/21_iR_GUI_num_C.png',
						'images_slice/21_iR_GUI_qui.png',
						'images_slice/21_iR_GUI_qui_C.png',
						'images_slice/22_iR_GUI_num.png',
						'images_slice/22_iR_GUI_num_C.png',
						'images_slice/22_iR_GUI_qui.png',
						'images_slice/22_iR_GUI_qui_C.png',
						'images_slice/23_iR_GUI_num.png',
						'images_slice/23_iR_GUI_num_C.png',
						'images_slice/23_iR_GUI_qui.png',
						'images_slice/23_iR_GUI_qui_C.png',
						'images_slice/24_iR_GUI_num.png',
						'images_slice/24_iR_GUI_num_C.png',
						'images_slice/24_iR_GUI_qui.png',
						'images_slice/24_iR_GUI_qui_C.png',
						'images_slice/25_iR_GUI_num.png',
						'images_slice/25_iR_GUI_num_C.png',
						'images_slice/25_iR_GUI_qui.png',
						'images_slice/25_iR_GUI_qui_C.png',
						'images_slice/26_iR_GUI_num.png',
						'images_slice/26_iR_GUI_num_C.png',
						'images_slice/26_iR_GUI_qui.png',
						'images_slice/26_iR_GUI_qui_C.png',
						'images_slice/27_iR_GUI_num.png',
						'images_slice/27_iR_GUI_num_C.png',
						'images_slice/27_iR_GUI_qui.png',
						'images_slice/27_iR_GUI_qui_C.png',
						'images_slice/28_iR_GUI_num.png',
						'images_slice/28_iR_GUI_num_C.png',
						'images_slice/28_iR_GUI_qui.png',
						'images_slice/28_iR_GUI_qui_C.png',
						'images_slice/29_iR_GUI_num.png',
						'images_slice/29_iR_GUI_num_C.png',
						'images_slice/29_iR_GUI_qui.png',
						'images_slice/29_iR_GUI_qui_C.png',
						'images_slice/30_iR_GUI_qui.png',
						'images_slice/30_iR_GUI_qui_C.png',
						'images_slice/31_iR_GUI_qui.png',
						'images_slice/31_iR_GUI_qui_C.png',
						'images_slice/32_iR_GUI_qui.png',
						'images_slice/32_iR_GUI_qui_C.png',
						'images_slice/01_iR_GUI_adv.png',
						'images_slice/01_iR_GUI_adv_C.png',
						'images_slice/01_iR_GUI_num.png',
						'images_slice/01_iR_GUI_num_C.png',
						'images_slice/01_iR_GUI_qui.png'
            ]
    });
    
$(function(){
    $('body').bind('turn', function(event, data){
          //alert(data.orientation); // landscape or profile
					if (data.orientation=='landscape')
					  {
					  alert('Please use this web app in portrait mode.');
					  }          
    });
    //swipe events
    $('#Tabelle_01').bind('swipe', function(event, data){
          //alert(data.direction);
					if (data.direction=='left')
					  {
					  setTimeout( "jQT.goTo($('#Tabelle_02'), 'fade')", 10);
					  }          
    });
    $('#Tabelle_02').bind('swipe', function(event, data){
          //alert(data.direction);
					if (data.direction=='right')
					  {
					  setTimeout( "jQT.goTo($('#Tabelle_01'), 'fade')", 10);
					  }          
					if (data.direction=='left')
					  {
					  setTimeout( "jQT.goTo($('#Tabelle_03'), 'fade')", 10);
					  }          
    });
    $('#Tabelle_03').bind('swipe', function(event, data){
          //alert(data.direction);
					if (data.direction=='right')
					  {
					  setTimeout( "jQT.goTo($('#Tabelle_02'), 'fade')", 10);
					  }          
    });
    
});